version: "3.9"

services:
  api:
    build: .
    container_name: boxers_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped